name: Mattermost Notifications

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published]

jobs:
  mattermost-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.MATTERMOST_WEBHOOK_URL != '' }}
    steps:
      - name: Send Mattermost notification
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          TEXT: |
            ### ${{ github.event_name }} - ${{ github.event.action }}
            
            **Repository**: ${{ github.repository }}
            **Actor**: ${{ github.actor }}
            
            ${{ github.event_name == 'pull_request' && format('**PR**: %s', github.event.pull_request.title) || '' }}
            ${{ github.event_name == 'issues' && format('**Issue**: %s', github.event.issue.title) || '' }}
            ${{ github.event_name == 'release' && format('**Release**: %s', github.event.release.name) || '' }}
            
            [View Details](${{ github.event_name == 'pull_request' && github.event.pull_request.html_url || github.event_name == 'issues' && github.event.issue.html_url || github.event.release.html_url }})