name: Custom Slack Notifications

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
    steps:
      - name: Notify on PR events
        if: github.event_name == 'pull_request'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#pull-requests'
          text: |
            Pull Request ${{ github.event.action }}: ${{ github.event.pull_request.title }}
            By: ${{ github.event.pull_request.user.login }}
            ${{ github.event.pull_request.html_url }}
            
            *Files changed*: ${{ github.event.pull_request.changed_files }}
            *Additions*: +${{ github.event.pull_request.additions }}
            *Deletions*: -${{ github.event.pull_request.deletions }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on issue events
        if: github.event_name == 'issues'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#issues'
          text: |
            Issue ${{ github.event.action }}: ${{ github.event.issue.title }}
            By: ${{ github.event.issue.user.login }}
            Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}
            ${{ github.event.issue.html_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on release
        if: github.event_name == 'release'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#releases'
          text: |
            🚀 New Release: ${{ github.event.release.name }}
            Tag: ${{ github.event.release.tag_name }}
            ${{ github.event.release.html_url }}
            
            ${{ github.event.release.body }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on CI completion
        if: github.event_name == 'workflow_run'
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          channel: '#ci-cd'
          text: |
            CI Workflow ${{ github.event.workflow_run.conclusion }}: ${{ github.event.workflow_run.name }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            Commit: ${{ github.event.workflow_run.head_commit.message }}
            ${{ github.event.workflow_run.html_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}