name: Typesense Integration

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published"]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  typesense-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.TYPESENSE_API_KEY != '' }}
    steps:
      - name: Send data to Typesense
        run: |
          payload=$(cat <<EOF
          {
            "event": "${{ github.event_name }}",
            "action": "${{ github.event.action }}",
            "repository": "${{ github.repository }}",
            "sender": "${{ github.actor }}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "data": ${{ toJSON(github.event) }}
          }
          EOF
          )
          
          curl -X POST \
            "${{ secrets.TYPESENSE_URL }}/collections/github-events/documents" \
            -H "X-TYPESENSE-API-KEY: ${{ secrets.TYPESENSE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$payload"