name: xMatters Integration

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  xmatters-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.XMATTERS_WEBHOOK_URL != '' }}
    steps:
      - name: Send xMatters alert on CI failure
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure'
        run: |
          curl -X POST \
            "${{ secrets.XMATTERS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "recipients": [
                {
                  "targetName": "${{ secrets.XMATTERS_RECIPIENT }}"
                }
              ],
              "subject": "CI Workflow Failed: ${{ github.event.workflow_run.name }}",
              "body": "The CI workflow has failed and requires attention.",
              "priority": "High",
              "properties": {
                "repository": "${{ github.repository }}",
                "workflow": "${{ github.event.workflow_run.name }}",
                "branch": "${{ github.event.workflow_run.head_branch }}",
                "commit": "${{ github.event.workflow_run.head_commit.message }}",
                "actor": "${{ github.event.workflow_run.head_commit.author.name }}",
                "url": "${{ github.event.workflow_run.html_url }}"
              }
            }'

      - name: Send xMatters alert on critical issues
        if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'critical')
        run: |
          curl -X POST \
            "${{ secrets.XMATTERS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "recipients": [
                {
                  "targetName": "${{ secrets.XMATTERS_RECIPIENT }}"
                }
              ],
              "subject": "Critical Issue Opened: ${{ github.event.issue.title }}",
              "body": "A critical issue has been opened and requires immediate attention.",
              "priority": "High",
              "properties": {
                "repository": "${{ github.repository }}",
                "issue": "${{ github.event.issue.title }}",
                "author": "${{ github.event.issue.user.login }}",
                "labels": "${{ join(github.event.issue.labels.*.name, ', ') }}",
                "url": "${{ github.event.issue.html_url }}"
              }
            }'