name: Pushwoosh Integration

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published"]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  pushwoosh-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.PUSHWOOSH_API_KEY != '' }}
    steps:
      - name: Send data to Pushwoosh
        run: |
          payload=$(cat <<EOF
          {
            "event": "${{ github.event_name }}_${{ github.event.action }}",
            "repository": "${{ github.repository }}",
            "sender": "${{ github.actor }}",
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "data": ${{ toJSON(github.event) }}
          }
          EOF
          )
          
          curl -X POST \
            "https://cp.pushwoosh.com/json/1.3/events" \
            -H "Content-Type: application/json" \
            -d '{
              "request": {
                "application": "${{ secrets.PUSHWOOSH_APP_CODE }}",
                "auth": "${{ secrets.PUSHWOOSH_API_KEY }}",
                "event": "'$payload'"
              }
            }'