name: Custom API Integration

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  custom-api-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.CUSTOM_API_URL != '' }}
    steps:
      - name: Send custom API notification
        run: |
          payload=$(cat <<EOF
          {
            "event": {
              "name": "${{ github.event_name }}",
              "action": "${{ github.event.action }}",
              "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            },
            "repository": {
              "name": "${{ github.repository }}",
              "url": "${{ github.repositoryUrl }}",
              "default_branch": "${{ github.event.repository.default_branch }}"
            },
            "sender": {
              "login": "${{ github.actor }}",
              "type": "${{ github.event.sender.type }}",
              "url": "${{ github.event.sender.html_url }}"
            },
            "data": ${{ toJSON(github.event) }}
          }
          EOF
          )
          
          curl -X POST \
            "${{ secrets.CUSTOM_API_URL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CUSTOM_API_TOKEN }}" \
            -H "X-Event-Type: ${{ github.event_name }}" \
            -H "X-Event-Action: ${{ github.event.action }}" \
            -d "$payload"