name: Pushover Notifications

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published]

jobs:
  pushover-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.PUSHOVER_USER_KEY != '' && secrets.PUSHOVER_APP_TOKEN != '' }}
    steps:
      - name: Send Pushover notification
        run: |
          curl -X POST \
            "https://api.pushover.net/1/messages.json" \
            -d "token=${{ secrets.PUSHOVER_APP_TOKEN }}" \
            -d "user=${{ secrets.PUSHOVER_USER_KEY }}" \
            -d "title=${{ github.event_name }} - ${{ github.event.action }}" \
            -d "message=${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event_name == 'issues' && github.event.issue.title || github.event.release.name }}" \
            -d "url=${{ github.event_name == 'pull_request' && github.event.pull_request.html_url || github.event_name == 'issues' && github.event.issue.html_url || github.event.release.html_url }}" \
            -d "url_title=View Details" \
            -d "priority=0" \
            -d "sound=pushover"