name: Bandwidth Integration

on:
  pull_request:
    types: [opened, closed, ready_for_review, merged]
  issues:
    types: [opened, closed, labeled]
  release:
    types: [published"]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  bandwidth-notify:
    runs-on: ubuntu-latest
    if: ${{ secrets.BANDWIDTH_API_USERNAME != '' && secrets.BANDWIDTH_API_PASSWORD != '' }}
    steps:
      - name: Send SMS via Bandwidth
        run: |
          message="GitHub Event: ${{ github.event_name }} - ${{ github.event.action }}. Repository: ${{ github.repository }}. Sender: ${{ github.actor }}."
          
          curl -X POST \
            "https://api.catapult.inetwork.com/v1/users/${{ secrets.BANDWIDTH_USER_ID }}/messages" \
            -u "${{ secrets.BANDWIDTH_API_USERNAME }}:${{ secrets.BANDWIDTH_API_PASSWORD }}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "${{ secrets.BANDWIDTH_FROM_NUMBER }}",
              "to": ["${{ secrets.BANDWIDTH_TO_NUMBER }}"],
              "text": "'$message'"
            }'