name: Email Notifications

on:
  pull_request:
    types: [opened, closed, ready_for_review]
  issues:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  send-email:
    runs-on: ubuntu-latest
    if: ${{ secrets.EMAIL_SMTP_HOST != '' }}
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SMTP_HOST }}
          server_port: ${{ secrets.EMAIL_SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: |
            ${{ github.event_name }}: ${{ github.event.repository.name }} - ${{ github.event.pull_request.title || github.event.issue.title || github.event.release.name }}
          to: ${{ secrets.EMAIL_RECIPIENTS }}
          from: GitHub Actions <${{ secrets.EMAIL_SENDER }}>
          body: |
            Repository: ${{ github.repository }}
            Event: ${{ github.event_name }}
            Action: ${{ github.event.action }}
            
            ${{ github.event.pull_request.html_url || github.event.issue.html_url || github.event.release.html_url }}
            
            ---
            Sent by GitHub Actions