name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 01:30 UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 30 days. Please add a comment or it will be marked as stale.'
          stale-pr-message: 'This pull request has been inactive for 30 days. Please add a comment or it will be marked as stale.'
          days-before-stale: 30
          days-before-close: 14
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-label: 'closed-stale'
          close-pr-label: 'closed-stale'
          exempt-issue-labels: 'pinned,security,help-wanted,good-first-issue'
          exempt-pr-labels: 'pinned,security,help-wanted,good-first-issue'